export type ColumnLayoutKey = '100' | '50-50' | '33-33-33' | '25-25-25-25' | '66-33' | '33-66';

/** Default `data` payloads per block type (aligned with hbcu-cms plan). */
export const BLOG_BLOCK_DEFAULTS = {
  paragraph: {
    text: '',
    align: 'left' as 'left' | 'center' | 'right' | 'justify',
    textColor: '',
    linkColor: '',
    hoverTextColor: '',
    hoverLinkColor: '',
    paragraphSpacing: 0,
    textShadow: { horizontal: 0, vertical: 0, blur: 0, color: 'rgba(0,0,0,0.25)' },
    marginTop: 0,
    marginBottom: 0,
    customClass: '',
  },
  heading: {
    text: '',
    level: 2,
    align: 'left' as 'left' | 'center' | 'right',
    color: '',
    marginTop: 0,
    marginBottom: 0,
    customClass: '',
  },
  image: {
    url: '',
    alt: '',
    caption: '',
    link: '',
    align: 'center' as 'left' | 'center' | 'right',
    width: 'full',
    /** Display scale within the column (% of container width). */
    scale: 100,
    brightness: 100,
    contrast: 100,
    saturation: 100,
    cropX: 0,
    cropY: 0,
    cropW: 100,
    cropH: 100,
    borderRadiusPx: 12,
    shadowPreset: 'md',
    borderWidthPx: 0,
    borderColor: '#e2e8f0',
    overlayColor: '#000000',
    overlayOpacity: 0,
    overlayBlendMode: 'normal',
    filterPreset: 'none',
    extraBlurPx: 0,
    extraGrayscale: 0,
    hueRotateDeg: 0,
    overlayTitle: '',
    overlaySubtitle: '',
    overlayPlacement: 'center',
    overlayTextColor: '#ffffff',
    overlayTextShadow: true,
    overlayTitleSize: 'lg',
    hoverEffect: 'none',
    marginTop: 0,
    marginBottom: 0,
    customClass: '',
  },
  video: {
    url: '',
    caption: '',
    autoplay: false,
    align: 'center' as 'left' | 'center' | 'right',
    aspectRatio: '16/9' as '16/9' | '4/3' | '1/1' | 'auto',
    maxWidth: 'full' as 'full' | 'wide' | 'medium',
    marginTop: 0,
    marginBottom: 0,
    customClass: '',
  },
  quote: { text: '', attribution: '', style: 'pullquote' },
  callout: { text: '', icon: '💡', variant: 'info' },
  divider: { style: 'line', color: '#E8B800' },
  spacer: { height: 48 },
  tabs: { tabs: [{ label: 'Tab 1', html: '' }, { label: 'Tab 2', html: '' }] },
  accordion: { items: [{ title: 'Section 1', html: '', open: false }] },
  slideshow: {
    slides: [{ url: '', alt: '', caption: '', credit: '' }],
    sliderVariant: 'single_focus' as 'peek_strip' | 'single_focus' | 'compact_row',
    autoplay: false,
    interval: 5000,
    transition: 'fade' as 'fade' | 'slide' | 'kenburns',
    transitionSpeed: 500,
    showArrows: true,
    showDots: true,
    showThumbs: false,
    showCounter: true,
    pauseOnHover: true,
    loop: true,
    autoplayInView: true,
    aspectRatio: '16/9' as '16/9' | '4/3' | '1/1' | 'auto',
    captionMode: 'below' as 'below' | 'overlay' | 'none',
    align: 'center' as 'left' | 'center' | 'right',
    maxHeightPx: 0,
    thumbSize: 'md' as 'sm' | 'md' | 'lg',
    arrowStyle: 'minimal' as 'minimal' | 'bold' | 'outside',
    dotStyle: 'dots' as 'dots' | 'bars',
    marginTop: 0,
    marginBottom: 0,
    customClass: '',
  },
  gallery: {
    images: [{ url: '', alt: '', caption: '', credit: '', focalX: 50, focalY: 50 }] as Array<{
      url: string;
      alt: string;
      caption: string;
      credit: string;
      focalX: number;
      focalY: number;
    }>,
    mode: 'grid' as 'grid' | 'masonry' | 'strip',
    columns: 3,
    gap: 16,
    aspectRatio: 'auto' as 'auto' | '1/1' | '4/3' | '16/9',
    lightbox: true,
    align: 'left' as 'left' | 'center' | 'right',
    marginTop: 0,
    marginBottom: 0,
    customClass: '',
  },
  carousel: {
    items: [{ url: '', alt: '', caption: '' }] as Array<{
      url: string;
      alt: string;
      caption: string;
      videoUrl?: string;
    }>,
    /** Visual preset: horizontal cards with peek, one-up hero, or tighter strip. */
    sliderVariant: 'peek_strip' as 'peek_strip' | 'single_focus' | 'compact_row',
    peekPx: 32,
    snap: true,
    showArrows: true,
    showDots: true,
    showThumbs: false,
    showCounter: false,
    autoplay: false,
    interval: 5000,
    pauseOnHover: true,
    transition: 'slide' as 'fade' | 'slide',
    aspectRatio: '16/9' as '16/9' | '4/3' | '1/1' | 'auto',
    loop: true,
    captionMode: 'below' as 'below' | 'overlay' | 'none',
    maxHeightPx: 0,
    thumbSize: 'md' as 'sm' | 'md' | 'lg',
    arrowStyle: 'minimal' as 'minimal' | 'bold' | 'outside',
    dotStyle: 'dots' as 'dots' | 'bars',
    autoplayInView: true,
    videoMutedAutoplay: false,
    transitionSpeed: 500,
    align: 'center' as 'left' | 'center' | 'right',
    marginTop: 0,
    marginBottom: 0,
    customClass: '',
    colsMobile: 1,
    colsTablet: 2,
    colsDesktop: 3,
  },
  html_embed: { html: '', sandboxed: true },
  social_embed: { input: '', caption: '' },
  code: { code: '', language: 'javascript', filename: '' },
  table: { rows: [['Header 1', 'Header 2'], ['Cell 1', 'Cell 2']], hasHeader: true },
  button: { text: 'Click here', url: '#', style: 'primary', align: 'left', size: 'md' },
  card: { title: '', body: '', image: '', link: '', linkText: 'Learn more' },
  banner: { text: '', subtext: '', bgColor: '#072a1b', textColor: '#FFFFFF', align: 'center' },
  map_embed: { src: '', height: 400 },
  tweet: { url: '', tweetId: '' },
  youtube: { videoId: '', caption: '', start: 0 },
  countdown: { targetDate: '', title: '', showDays: true, showHours: true, showMinutes: true },
  stats: { items: [{ value: '1K+', label: 'Alumni', icon: '🎓' }], columns: 3 },
  timeline: {
    variant: 'story_dark' as 'story_dark' | 'minimal',
    /** Optional hero quote (story_dark) */
    quoteText: '',
    quoteAttribution: '',
    /** e.g. THE TIMELINE */
    sectionLabel: 'THE TIMELINE',
    items: [
      {
        year: '1870',
        title: '15th Amendment ratified.',
        body: 'Black men gain the constitutional right to vote.',
      },
    ],
    direction: 'vertical',
  },
  /** Voting-rights-style stats strip + checklist (paired with Timeline story_dark). */
  story_metrics: {
    /** `full` = one strip; `spotlight` | `stats` | `actions` = split segment (same picker type). */
    layout: 'full' as 'full' | 'spotlight' | 'stats' | 'actions',
    /** Outer shell background (hex/rgb). Empty = default navy theme. */
    shellBg: '',
    /** “Actions” inset panel background. Empty = default. */
    insetBg: '',
    spotlightYear: '2026',
    spotlightLead: 'Callais v. Louisiana.',
    spotlightBody:
      'The Supreme Court clears the way for vote dilution. Turnout differs sharply by precinct—verify claims with county data.',
    stats: [
      {
        value: '6.7%',
        label: 'BEFORE VRA',
        caption: 'Mississippi Black voter registration before 1965',
        accent: 'sky' as 'sky' | 'gold' | 'slate',
      },
      {
        value: '~60%',
        label: 'AFTER VRA',
        caption: 'Within years of the Voting Rights Act',
        accent: 'gold',
      },
      {
        value: '100+',
        label: 'RESTRICTIVE LAWS',
        caption: 'Passed by states in the decade after Shelby County',
        accent: 'sky',
      },
    ],
    actionsTitle: 'What you can do right now.',
    actions: ['Check your voter registration', 'Vote in every election (local races set the maps)', 'Volunteer as a poll worker'],
  },
  team: { members: [{ name: '', role: '', image: '', bio: '' }], columns: 3, layout: 'grid' as 'grid' | 'scroll' },
  newsletter: {
    title: 'Stay Connected',
    subtitle: 'Get the receipts in your inbox',
    placeholder: 'Your email address',
    buttonText: 'Subscribe',
  },
  poll: { question: '', options: ['Option A', 'Option B'], allowMultiple: false },
  progress: { items: [{ label: '', value: 75, color: '#E8B800' }] },
  galaxy: { starCount: 200, speed: 0.5, colorMode: 'gold', height: 400, text: '', subtext: '' },
  audio: { url: '', title: '', artist: '' },
  file_download: { url: '', filename: '', description: '', size: '' },
  /** Structured quote + attribution + optional portrait (reviews / testimonials). */
  testimonial: { quote: '', name: '', role: '', imageUrl: '', rating: 5 },
  /** Single feature / service highlight with emoji or short glyph. */
  icon_box: { icon: '🎓', title: '', body: '' },
  /** Stacked or grid of YouTube embeds (playlist-style). */
  video_playlist: {
    playlistTitle: 'Playlist',
    videos: [{ videoId: '', title: '' }] as Array<{ videoId: string; title: string }>,
    layout: 'player' as 'player' | 'stack' | 'grid',
  },
  /** Post grid — manual cards or auto “related” from `publisher_blog_posts`. */
  post_teasers: {
    mode: 'latest' as 'manual' | 'latest',
    heading: 'Related posts',
    limit: 3,
    relatedBy: 'category' as 'category' | 'recent',
    items: [{ title: '', slug: '', excerpt: '', imageUrl: '' }] as Array<{
      title: string;
      slug: string;
      excerpt: string;
      imageUrl: string;
    }>,
    columns: 2 as 2 | 3,
  },
  columns: {
    layout: '50-50' as ColumnLayoutKey,
    gap: 24,
    columnWidths: [50, 50],
    columns: [{ blocks: [] }, { blocks: [] }],
    marginTop: 0,
    marginBottom: 0,
    paddingY: 0,
    customClass: '',
  },
  /** Mailto CTA (contact strip). */
  contact_cta: { title: 'Get in touch', body: '', email: '', buttonLabel: 'Email us' },
  /** Simple price / services list. */
  price_list: { heading: '', items: [{ label: '', price: '', detail: '' }] },
  /** Popover overlay (uses Popover API — no inline JS). */
  modal_popup: {
    triggerLabel: 'Open',
    title: '',
    body: '',
    alignTrigger: 'left' as 'left' | 'center' | 'right',
  },
  /** CSS-only animated headline (fade-up words, gradient sweep, or underline draw). */
  animated_headline: {
    text: 'Excellence in motion.',
    variant: 'fade-up' as 'fade-up' | 'gradient' | 'underline',
    level: 2 as 1 | 2 | 3,
  },
  /** I Call BS brand sections — rendered with the kit classes in `src/styles.css`. */
  kit_hero: {
    tag: 'Free Starter Kit',
    tagline: 'Practical. Honest. Receipts-driven.',
    coverUrl: '/img/kit-cover.png',
    coverAlt: 'Cover of the I Call BS Free Starter Kit',
    headlineBefore: 'The ',
    highlight: 'honest',
    headlineAfter: ' version of “build an app with AI.”',
    subhead:
      'No fairy tales. No thirty-minute miracles. The myth-busting, the mindset, and just enough of the toolkit to prove it’s real.',
    showForm: true,
    showNav: true,
    buttonLabel: 'Send me the free kit',
    buttonHref: '',
    button2Label: '',
    button2Href: '',
    anchor: '',
    receipts: [
      { value: '221', label: 'Chat sessions' },
      { value: '3,302', label: 'Prompts I typed' },
      { value: '16,612', label: 'File edits by the AI' },
      { value: '4,338', label: 'Terminal commands' },
    ] as Array<{ value: string; label: string }>,
  },
  kit_contents: {
    tone: 'cream' as KitTone,
    label: 'Inside the kit',
    heading: 'What this free kit is',
    lede: 'The myth-busting, the mindset, and just enough of the toolkit to prove it’s real.',
    ledeHighlight: 'Everything here is yours to copy, edit, and keep.',
    layout: 'list' as 'list' | 'compare',
    columns: [
      { heading: 'Free starter kit', note: 'Free', ctaLabel: '', ctaHref: '', items: [{ title: '' }] },
      { heading: 'The full edition', note: '$17', ctaLabel: '', ctaHref: '', items: [{ title: '' }] },
    ] as Array<{ heading: string; note: string; ctaLabel: string; ctaHref: string; items: Array<{ title: string }> }>,
    groups: [] as Array<{ label: string; kitCount: string; bookCount: string; rows: Array<{ title: string; kit: string; book: string }> }>,
    items: [
      { number: '01', title: 'Myth vs Reality', kind: 'Part 01' },
      { number: '02', title: 'AI Is Not Smarter Than You', kind: 'Part 02' },
      { number: '03', title: 'Three Lessons from the Receipts', kind: 'Part 03' },
      { number: '04', title: 'The Literacy Gate', kind: 'Part 04' },
      { number: '05', title: 'The Toolkit', kind: 'Part 05' },
      { number: '—', title: 'Where to Go from Here', kind: 'Next step' },
      { number: '—', title: 'The Pocket Glossary', kind: 'Glossary' },
      { number: '—', title: 'Proof Your Work', kind: 'Checklist' },
      { number: '—', title: 'The Smoke Test', kind: 'Checklist' },
      { number: '—', title: 'Before You Ship', kind: 'Checklist' },
    ] as Array<{ number: string; title: string; kind: string }>,
  },
  kit_gallery: {
    tone: 'white' as KitTone,
    label: 'Look inside',
    heading: 'Real pages from the kit.',
    images: [
      { url: '/img/preview-receipts.jpg', alt: 'Kit page: My Receipts' },
      { url: '/img/preview-gap.jpg', alt: 'Kit page: That’s not a knowledge gap. That’s an experience gap.' },
      { url: '/img/preview-smoke.jpg', alt: 'Kit page: The Smoke Test' },
    ] as Array<{ url: string; alt: string }>,
    caption: 'My receipts · Not a knowledge gap · The smoke test',
  },
  kit_closing: {
    tone: 'green' as KitTone,
    headlineBefore: 'You bring the depth. It brings the breadth. ',
    highlight: 'Neither one ships alone.',
    label: 'Get the free starter kit',
    buttonLabel: 'Send me the free kit',
  },
  kit_text: {
    tone: 'cream' as KitTone,
    label: 'Label',
    heading: 'Section heading',
    body: 'Write the section copy here.',
    highlight: '',
    centered: false,
    buttonLabel: '',
    buttonHref: '',
    anchor: '',
    showImage: false,
    imageUrl: '',
    imageAlt: '',
  },
  kit_signup: {
    tone: 'green' as KitTone,
    label: 'Get the free starter kit',
    heading: '',
    buttonLabel: 'Send me the free kit',
  },
  kit_questions: {
    tone: 'cream' as KitTone,
    greeting: 'Dear builder,',
    questions: [
      { text: 'Were you told you could build a whole app in thirty minutes with one prompt?' },
      { text: 'Have you asked the AI to fix one small thing and watched it change five others?' },
      { text: 'Has the AI told you "fixed" when it wasn\'t?' },
      { text: 'Or does your app work fine for you and fall apart the moment someone else tries it?' },
    ] as Array<{ text: string }>,
    heading: 'Me too.',
    body: 'I believed a softer version of that story longer than I should have. Then I built real apps with Claude Code and Cursor. It took 3,302 prompts across 221 chats, and about one in six of them was a correction.',
    buttonLabel: 'Send me the free kit',
    buttonHref: '#kit',
    anchor: '',
  },
} as const;

export type KitTone = 'green' | 'cream' | 'white';

export const KIT_BLOCK_TYPES = ['kit_hero', 'kit_contents', 'kit_gallery', 'kit_closing', 'kit_text', 'kit_signup', 'kit_questions'] as const;

export function isKitBlockType(type: string): boolean {
  return (KIT_BLOCK_TYPES as readonly string[]).includes(type);
}

export type BlogBlockType = keyof typeof BLOG_BLOCK_DEFAULTS;

export type BlogBlock = {
  id: string;
  type: string;
  data: Record<string, unknown>;
};

/** Block types exposed in the admin picker (subset; more can be added over time). */
export const BLOG_EDITOR_PICKER_TYPES: BlogBlockType[] = [
  'paragraph',
  'heading',
  'image',
  'video',
  'quote',
  'callout',
  'divider',
  'spacer',
  'youtube',
  'social_embed',
  'galaxy',
  'code',
  'tabs',
  'accordion',
  'columns',
  'slideshow',
  'gallery',
  'carousel',
  'timeline',
  'story_metrics',
  'button',
  'banner',
  'card',
  'countdown',
  'stats',
  'team',
  'table',
  'map_embed',
  'testimonial',
  'icon_box',
  'video_playlist',
  'post_teasers',
  'contact_cta',
  'price_list',
  'newsletter',
  'modal_popup',
  'animated_headline',
  ...KIT_BLOCK_TYPES,
];

export const BLOG_BLOCK_LABELS: Record<BlogBlockType, string> = {
  paragraph: 'Paragraph',
  heading: 'Heading',
  image: 'Image',
  video: 'Video',
  quote: 'Quote',
  callout: 'Callout',
  divider: 'Divider',
  spacer: 'Spacer',
  columns: 'Columns',
  tabs: 'Tabs',
  accordion: 'Accordion',
  slideshow: 'Slideshow',
  gallery: 'Gallery',
  carousel: 'Carousel',
  html_embed: 'HTML Embed',
  social_embed: 'Social embed',
  code: 'Code',
  table: 'Table',
  button: 'Button',
  card: 'Card',
  banner: 'Banner',
  map_embed: 'Map',
  tweet: 'Tweet',
  youtube: 'YouTube',
  countdown: 'Countdown',
  stats: 'Stats',
  timeline: 'Timeline',
  team: 'Team',
  newsletter: 'Newsletter',
  poll: 'Poll',
  progress: 'Progress',
  galaxy: 'Galaxy',
  audio: 'Audio',
  file_download: 'File',
  story_metrics: 'Story stats / CTA',
  testimonial: 'Testimonial',
  icon_box: 'Icon box',
  video_playlist: 'Video playlist',
  post_teasers: 'Latest posts',
  contact_cta: 'Contact CTA',
  price_list: 'Price list',
  modal_popup: 'Popup / modal',
  animated_headline: 'Animated headline',
  kit_hero: 'Kit hero + signup',
  kit_contents: 'Contents section',
  kit_gallery: 'Image row',
  kit_closing: 'Closing CTA',
  kit_text: 'Text section',
  kit_signup: 'Signup section',
  kit_questions: 'Questions',
};

// Branded Lucide replacement for the editor's block-type glyphs. The
// previous map mixed text symbols and emojis — this map gives the block
// picker and the draggable list a consistent line-icon look that
// matches the rest of the platform chrome (Navbar, Toolkit, etc).
import {
  AlertCircle,
  AlignJustify,
  AlignLeft,
  AudioLines,
  BadgeDollarSign,
  BarChart3,
  BookOpen,
  Code as CodeIcon,
  Columns,
  Download,
  FileCode,
  Frame,
  GalleryHorizontal,
  GalleryVerticalEnd,
  Hexagon,
  Image as ImageBlockIcon,
  LayoutGrid,
  LayoutTemplate,
  ListChecks,
  ListOrdered,
  ListVideo,
  Mail,
  MapPin as MapPinBlockIcon,
  Megaphone,
  MessageCircleMore,
  Minus,
  MousePointer,
  Music,
  PanelTop,
  Pilcrow,
  Presentation,
  Quote,
  Send,
  Share2,
  Sparkles as SparklesIcon,
  SquareStack,
  Table as TableIcon,
  Timer,
  TrendingUp,
  Type as TypeIcon,
  Users as UsersBlockIcon,
  Video as VideoBlockIcon,
  Vote,
  Youtube,
  type LucideIcon,
} from 'lucide-react';

export const BLOG_BLOCK_ICONS: Record<BlogBlockType, LucideIcon> = {
  paragraph: Pilcrow,
  heading: TypeIcon,
  image: ImageBlockIcon,
  video: VideoBlockIcon,
  quote: Quote,
  callout: AlertCircle,
  divider: Minus,
  spacer: AlignLeft,
  columns: Columns,
  tabs: PanelTop,
  accordion: AlignJustify,
  slideshow: Presentation,
  gallery: LayoutGrid,
  carousel: GalleryHorizontal,
  html_embed: FileCode,
  social_embed: Share2,
  code: CodeIcon,
  table: TableIcon,
  button: MousePointer,
  card: LayoutTemplate,
  banner: Megaphone,
  map_embed: MapPinBlockIcon,
  tweet: MessageCircleMore,
  youtube: Youtube,
  countdown: Timer,
  stats: BarChart3,
  timeline: GalleryVerticalEnd,
  team: UsersBlockIcon,
  newsletter: Mail,
  poll: Vote,
  progress: TrendingUp,
  galaxy: SparklesIcon,
  audio: AudioLines,
  file_download: Download,
  story_metrics: BarChart3,
  testimonial: Quote,
  icon_box: Hexagon,
  video_playlist: ListVideo,
  post_teasers: SquareStack,
  contact_cta: Send,
  price_list: BadgeDollarSign,
  modal_popup: Frame,
  animated_headline: SparklesIcon,
  kit_hero: BookOpen,
  kit_contents: ListOrdered,
  kit_gallery: GalleryHorizontal,
  kit_closing: Megaphone,
  kit_text: TypeIcon,
  kit_signup: Mail,
  kit_questions: ListChecks,
};

export const BLOG_EDITOR_PICKER_CATEGORIES: Record<string, BlogBlockType[]> = {
  Brand: [...KIT_BLOCK_TYPES],
  Text: ['paragraph', 'heading', 'animated_headline', 'quote', 'callout', 'code', 'table'],
  Media: ['image', 'video', 'youtube', 'social_embed', 'slideshow', 'gallery', 'carousel', 'video_playlist'],
  Layout: ['columns', 'divider', 'spacer', 'tabs', 'accordion', 'button', 'banner', 'card', 'icon_box', 'modal_popup'],
  Marketing: [
    'stats',
    'countdown',
    'testimonial',
    'price_list',
    'contact_cta',
    'newsletter',
    'post_teasers',
  ],
  Story: ['timeline', 'story_metrics', 'team', 'map_embed'],
  Special: ['galaxy'],
};
