export const ADMIN_NAV = [
  { href: '/admin', label: 'Dashboard', phase: 1 },
  { href: '/admin/pages', label: 'Pages', phase: 1 },
  { href: '/admin/posts', label: 'Blog Posts', phase: 5 },
  { href: '/admin/media', label: 'Media Library', phase: 3 },
  { href: '/admin/templates', label: 'Templates', phase: 5 },
  { href: '/admin/appearance', label: 'Appearance', phase: 6 },
  { href: '/admin/menus', label: 'Navigation', phase: 6 },
  { href: '/admin/forms', label: 'Forms', phase: 6 },
  { href: '/admin/users', label: 'Users & Roles', phase: 6 },
  { href: '/admin/seo', label: 'SEO & Redirects', phase: 6 },
  { href: '/admin/settings', label: 'Settings', phase: 6 },
  { href: '/admin/activity', label: 'Activity', phase: 6 },
  { href: '/admin/import', label: 'Import / Export', phase: 7 },
] as const
