import type { LucideIcon } from 'lucide-react'
import {
  BookOpen,
  Columns,
  Download,
  GalleryHorizontal,
  LayoutGrid,
  Mail,
  Megaphone,
  Quote,
  Send,
  SquareStack,
  Type,
  Users,
} from 'lucide-react'

/** Block types for the VettaJimale.Tech brand pages. Rendered by BrandBlockView, edited in the studio. */
export const BRAND_BLOCK_TYPES = [
  'brand_hero',
  'brand_topics',
  'brand_columns',
  'brand_cards',
  'brand_projects',
  'brand_product',
  'brand_newsletter',
  'brand_library',
  'brand_quote',
  'brand_contact',
  'brand_catalog',
  'brand_previews',
  'brand_compare',
  'brand_faq',
  'brand_thanks',
  'brand_article',
] as const

export function isBrandBlockType(type: string): boolean {
  return (BRAND_BLOCK_TYPES as readonly string[]).includes(type)
}

const item = { title: '', text: '', meta: '', href: '', format: '', topic: '', sample: false, featured: false }

export const BRAND_BLOCK_DEFAULTS = {
  brand_hero: {
    eyebrow: '',
    headline: '',
    highlight: '',
    statement: '',
    mediaLabel: 'Your photo or welcome video',
    photoUrl: '',
    mediaUrl: '',
    primaryLabel: '',
    primaryHref: '',
    secondaryLabel: '',
    secondaryHref: '',
    showForm: false,
  },
  brand_topics: { label: '', heading: '', items: [item] },
  brand_columns: { label: '', heading: '', items: [item] },
  brand_cards: { label: '', heading: '', linkLabel: '', linkHref: '', items: [item] },
  brand_projects: { label: '', heading: '', note: '', items: [item] },
  brand_product: {
    label: 'My first book',
    title: '',
    text: '',
    price: '$17',
    coverUrl: '/img/book-cover.png',
    coverAlt: 'Cover of I Call BS: AI Vibe Coding Myths Dispelled',
    primaryLabel: 'Explore the book',
    primaryHref: '/products/i-call-bs',
    secondaryLabel: 'Get the free kit',
    secondaryHref: '/free-kit',
    note: '',
  },
  brand_newsletter: {
    heading: 'Stay curious.',
    text: 'Occasional notes from VJ. Unsubscribe anytime.',
    buttonLabel: 'Subscribe',
  },
  brand_library: { heading: '', lede: '', items: [item] },
  brand_quote: { heading: '', text: '', mediaLabel: 'Your introduction video', videoUrl: '' },
  brand_contact: { headline: '', highlight: '', lede: '', items: [item] },
  brand_catalog: { heading: '', lede: '', note: '', items: [item] },
  brand_previews: { label: '', heading: '', items: [{ ...item, href: '' }] },
  brand_compare: {
    heading: '',
    kitHeading: 'Free kit',
    bookHeading: 'Complete book',
    rows: [{ label: '', kit: '', book: '' }],
  },
  brand_faq: { heading: '', items: [item] },
  brand_thanks: {
    heading: 'Your free kit is ready.',
    text: 'Download the PDF below. We’ll also email you a copy.',
    downloadLabel: 'Download the Free Kit (PDF)',
    downloadHref: '/downloads/I-Call-BS-Free-Starter-Kit.pdf',
    steps: [{ title: '', text: '' }],
    bookTitle: '',
    bookText: '',
    bookPrice: '$17',
    bookLabel: 'Get the Complete Book — $17',
    bookHref: '/products/i-call-bs',
    bookNote: 'Your kit is yours whether you buy or not.',
    resourcesLabel: 'Browse Free Resources',
    resourcesHref: '/resources',
  },
  brand_article: { eyebrow: '', heading: '', lede: '', items: [item], bookHref: '/products/i-call-bs', bookLabel: 'The complete book' },
} as const

export const BRAND_BLOCK_LABELS: Record<(typeof BRAND_BLOCK_TYPES)[number], string> = {
  brand_hero: 'Brand hero',
  brand_topics: 'Topic cards',
  brand_columns: 'Three columns',
  brand_cards: 'Resource cards',
  brand_projects: 'Project slots',
  brand_product: 'Book feature',
  brand_newsletter: 'Newsletter',
  brand_library: 'Resource library',
  brand_quote: 'Quote and video',
  brand_contact: 'Contact',
  brand_catalog: 'Product catalog',
  brand_previews: 'Page screenshots',
  brand_compare: 'Kit and book comparison',
  brand_faq: 'Questions',
  brand_thanks: 'Kit download',
  brand_article: 'Resource article',
}

export const BRAND_BLOCK_ICONS: Record<(typeof BRAND_BLOCK_TYPES)[number], LucideIcon> = {
  brand_hero: Type,
  brand_topics: LayoutGrid,
  brand_columns: Columns,
  brand_cards: SquareStack,
  brand_projects: GalleryHorizontal,
  brand_product: BookOpen,
  brand_newsletter: Mail,
  brand_library: SquareStack,
  brand_quote: Quote,
  brand_contact: Send,
  brand_catalog: LayoutGrid,
  brand_previews: GalleryHorizontal,
  brand_compare: Columns,
  brand_faq: Megaphone,
  brand_thanks: Download,
  brand_article: Users,
}
